### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by wuying1984** [uubram/RTCR#18]
Hi, I downloaded the zip file to our cluster and use the code "python setup.py intall --myaccount" and got the following error.

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import rtcr
  File "/home/wuy24/program/software/rtcr/RTCR/rtcr/__init__.py", line 1, in <module>
    from __main__ import __version__
ImportError: cannot import name '__version__' from '__main__' (setup.py)

Do you know why I got this error? Thanks!

**Comment by uubram** [comment]
Use python 2 to install and run RTCR, and use "python setup.py install --user" as installation command. Note, RTCR was developed and tested using python version 2.7.3. Please let me know if this resolves your error.

Best wishes,
Bram

**Comment by wuying1984** [comment]
Hi Bram, 

The RTCR should be successfully installed in our cluster. But When I run the following command, I got some error.
Command:
rtcr run -i ../wt_S1_merged.fastq --species MusMusculus --gene TRA --no_VJ_collapsing -t 8 1>rtcr.log 2>rtcr.err

Error:
Exception in thread Pipeline:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/mnt/nasapps/development/RTCR/0.5.1/lib64/python2.7/site-packages/rtcr-0.5.1-py2.7-linux-x86_64.egg/rtcr/pipeline.py", line 293, in run
    self._clone_classname)
  File "/mnt/nasapps/development/RTCR/0.5.1/lib64/python2.7/site-packages/rtcr-0.5.1-py2.7-linux-x86_64.egg/rtcr/clone.py", line 536, in build_clone
    other = (nt_jnc, q_jnc, 1))
  File "/mnt/nasapps/development/RTCR/0.5.1/lib64/python2.7/site-packages/rtcr-0.5.1-py2.7-linux-x86_64.egg/rtcr/clone.py", line 171, in __init__
    super(AnnotatedClone, self).__init__(*args, **kwargs)
  File "/mnt/nasapps/development/RTCR/0.5.1/lib64/python2.7/site-packages/rtcr-0.5.1-py2.7-linux-x86_64.egg/rtcr/clone.py", line 54, in __init__
    self._cqs = ConsensusQSequence(other)
ValueError: Quality score of 'N' should be 0.

Could you help me to fix the error? Thanks!
Best,
Ying

**Comment by uubram** [comment]
Hi Ying,

Your error has been answered in another thread, please check out [ValueError: Quality score of 'N' should be 0](https://github.com/uubram/RTCR/issues/3).

Best wishes,
Bram

**Comment by wuying1984** [comment]
Hi Bram,

The above problem was solved. And the alignment was finished successfully and I can see the results.tsv file. However, I got another error shown in the error message of the following command. 

Command:
rtcr run -i ../wt_S1_merged.fastq --species MusMusculus --gene TRA --no_VJ_collapsing -t 8 1>rtcr.log 2>rtcr.err

Error in rtcr.err
Unable to parse the pattern

Do you know what happened? And whether the result file is correct? Thank you  very much!

Best,
Ying

**Comment by uubram** [comment]
Since your install issue has been resolved, I am closing this thread. Please check out your ["Unable to parse the pattern" ](https://github.com/uubram/RTCR/issues/19) issue in the new thread that I opened.
